#!/usr/bin/env python3
"""Backs the manuscript's Cohen-kappa, Friedman-omnibus, and Bonferroni claims.

Section 2.7 states Cohen kappa was a secondary metric and that "the Friedman
omnibus was used for multi-way comparisons; the Bonferroni correction was
applied where appropriate." This script computes those statistics from the
committed per-fold artifacts and writes results/extra_stats.json, so the
numbers reported in Sections 3.1-3.2 are reproducible.

  * Cohen kappa: per-fold from y_true/y_pred in results/per_class_per_fold.json
    (v1 GAT and v2 GigaPath-DefGNN), 5-fold mean +/- population std (ddof=0).
  * Friedman omnibus: scipy.stats.friedmanchisquare on per-fold balanced
    accuracy across model sets (all ten aggregators; the four static-graph
    backbones).
  * Bonferroni: proposed vs each of the nine baselines (paired t-test),
    corrected at m = 9.

Run:  PYTHONPATH=. python3 scripts/17_extra_stats.py
Out:  results/extra_stats.json
"""

from __future__ import annotations

import json
import pathlib

import numpy as np
from scipy import stats
from sklearn.metrics import cohen_kappa_score

ROOT = pathlib.Path(__file__).resolve().parent.parent


def _bacc(rel: str) -> np.ndarray:
    s = json.loads((ROOT / rel).read_text())
    return np.asarray(s["metrics"]["val_balanced_accuracy"]["fold_values"], dtype=float)


def main() -> None:
    # ---- Cohen kappa (v1 GAT, v2 DefGNN) ----
    pcf = json.loads((ROOT / "results/per_class_per_fold.json").read_text())
    kappa = {}
    for tag, name in [("v1", "GAT"), ("v2", "GigaPath-DefGNN")]:
        ks = np.array([cohen_kappa_score(f["y_true"], f["y_pred"]) for f in pcf[tag]])
        kappa[name] = {
            "per_fold": [round(float(x), 6) for x in ks],
            "mean": round(float(ks.mean()), 6),
            "pop_std": round(float(ks.std(ddof=0)), 6),
        }
    kappa["delta"] = round(kappa["GigaPath-DefGNN"]["mean"] - kappa["GAT"]["mean"], 6)

    # ---- per-fold balanced accuracy for all models ----
    models = {
        "GAT": _bacc("results/v1_reference/v1_baseline_summary.json"),
        "GigaPath-DefGNN": _bacc("results/deformable/summary.json"),
    }
    for m in ["abmil", "dsmil", "transmil", "clam_sb", "clam_mb"]:
        models[m.upper()] = _bacc(f"results/mil_baselines/{m}/summary.json")
    # per-fold GCN/GraphSAGE/GIN values (formerly paper/figures/fig3_baseline_data.json)
    f3 = json.loads((ROOT / "results/v1_reference/v1_architecture_per_fold.json").read_text())
    for row in f3:
        lab = (row.get("label_pretty") or row.get("label") or row.get("group_pretty") or "").lower()
        folds = row.get("per_fold") or row.get("folds") or row.get("scores")
        for nm, key in {"gcn": "GCN", "graphsage": "GraphSAGE", "gin": "GIN"}.items():
            if lab.endswith(nm) and folds and key not in models:
                models[key] = np.asarray(folds, dtype=float)

    # ---- Friedman omnibus ----
    all10 = ["GCN", "GIN", "GraphSAGE", "GAT", "ABMIL", "DSMIL", "TRANSMIL", "CLAM_SB", "CLAM_MB", "GigaPath-DefGNN"]
    backbones4 = ["GCN", "GIN", "GraphSAGE", "GAT"]

    def friedman(names):
        chi2, p = stats.friedmanchisquare(*[models[n] for n in names])
        return {"models": names, "chi2": round(float(chi2), 4), "df": len(names) - 1, "p": float(p)}

    friedman_res = {
        "all_ten_aggregators": friedman(all10),
        "four_static_graph_backbones": friedman(backbones4),
    }

    # ---- Bonferroni: proposed vs 9 baselines (paired t) ----
    prop = models["GigaPath-DefGNN"]
    comps = [m for m in all10 if m != "GigaPath-DefGNN"]
    m_comp = len(comps)
    alpha = 0.05
    posthoc = {}
    for m in comps:
        t, p = stats.ttest_rel(prop, models[m])
        posthoc[m] = {
            "paired_t_p": round(float(p), 6),
            "p_bonferroni": round(float(min(p * m_comp, 1.0)), 6),
            "significant_at_corrected_alpha": bool(p < alpha / m_comp),
        }

    result = {
        "description": (
            "Cohen kappa, Friedman omnibus, and Bonferroni post-hoc backing "
            "Sections 3.1-3.2. Generated by scripts/17_extra_stats.py."
        ),
        "cohen_kappa": kappa,
        "friedman_omnibus": friedman_res,
        "bonferroni_posthoc": {
            "comparisons": m_comp,
            "corrected_alpha": round(alpha / m_comp, 6),
            "proposed_vs_baseline": posthoc,
        },
    }
    out = ROOT / "results" / "extra_stats.json"
    out.write_text(json.dumps(result, indent=2) + "\n")

    print(f"Cohen kappa  GAT={kappa['GAT']['mean']:.3f}+/-{kappa['GAT']['pop_std']:.3f}  "
          f"DefGNN={kappa['GigaPath-DefGNN']['mean']:.3f}+/-{kappa['GigaPath-DefGNN']['pop_std']:.3f}  "
          f"d={kappa['delta']:+.3f}")
    for k, v in friedman_res.items():
        print(f"Friedman {k}: chi2={v['chi2']}, df={v['df']}, p={v['p']:.4g}")
    print(f"Bonferroni (alpha/9={alpha/m_comp:.4f}) survivors: "
          f"{[m for m, r in posthoc.items() if r['significant_at_corrected_alpha']]}")
    print(f"\nWrote {out}")


if __name__ == "__main__":
    main()
